# Problem 2

In [105]:
import numpy as np
import random

In [106]:
def ret_sums(state):
    row_sum = np.sum(state, axis=0)
    col_sum = np.sum(state, axis=1)
    diag_sum = np.array([int(state[0,0])+int(state[1,1])+int(state[2,2]), int(state[2,0])+ int(state[1,1])+ int(state[0,2])])
    return row_sum, col_sum, diag_sum

In [107]:
def check_win(state):
    temp_state = state == 1
    row_sum, col_sum, diag_sum = ret_sums(temp_state)
    check1 = max([np.sum(row_sum>2), np.sum(col_sum>2), np.sum(diag_sum>2)])
    temp_state = state == -1
    row_sum, col_sum, diag_sum = ret_sums(temp_state)
    check2 = max([np.sum(row_sum>2), np.sum(col_sum>2), np.sum(diag_sum>2)])
    return max(check1, check2)

In [113]:
state = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
while not check_win(state):
    print(state)
    valid = True
    while valid:
        print('Enter coordinate: x')
        p1x = input()
        print('Enter coordinate: y')
        p1y = input()        
        try:
            if state[int(p1x),int(p1y)] != 0:
                print('Invalid, try again.')
            else:
                state[int(p1x),int(p1y)] = 1
                valid = False
        except:
            print('Invalid, try again.')
    if check_win(state):
            print('player 1 wins!')
            break
    try:
        avail_cords = [(i,j) for i,j in zip(*np.where(state==0))]
        state[random.choice(avail_cords)] = -1
        # bellman equation should go something like this: cycle through the available coords, if can win now, choose that point, o/w min continuation value (check_win for p1)
    except:
        if not check_win(state):
            print('draw')
    finally:
        if check_win(state):
            print('player 2 wins!')
            break
print(state)
state = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Enter coordinate: x
0
Enter coordinate: y
0
[[ 1  0  0]
 [ 0  0  0]
 [ 0  0 -1]]
Enter coordinate: x
0
Enter coordinate: y
1
[[ 1  1 -1]
 [ 0  0  0]
 [ 0  0 -1]]
Enter coordinate: x
1
Enter coordinate: y
0
[[ 1  1 -1]
 [ 1  0  0]
 [ 0 -1 -1]]
Enter coordinate: x
2
Enter coordinate: y
0
player 1 wins!
[[ 1  1 -1]
 [ 1  0  0]
 [ 1 -1 -1]]
