# Problem 2

In [1]:
import numpy as np
import random

In [2]:
def ret_sums(state):
    row_sum = np.sum(state, axis=0)
    col_sum = np.sum(state, axis=1)
    diag_sum = np.array([int(state[0,0])+int(state[1,1])+int(state[2,2]), int(state[2,0])+ int(state[1,1])+ int(state[0,2])])
    return row_sum, col_sum, diag_sum

In [3]:
def check_win(state):
    temp_state = state == 1
    row_sum, col_sum, diag_sum = ret_sums(temp_state)
    check1 = max([np.sum(row_sum>2), np.sum(col_sum>2), np.sum(diag_sum>2)])
    temp_state = state == -1
    row_sum, col_sum, diag_sum = ret_sums(temp_state)
    check2 = max([np.sum(row_sum>2), np.sum(col_sum>2), np.sum(diag_sum>2)])
    return max(check1, check2)

In [4]:
state = np.array([[0, 0, 0], [0, 0, 0], [-1, 0, 0]])
while not check_win(state):
    print(state)
    valid = True
    while valid:
        print('Enter coordinate: row')
        p1x = input()
        print('Enter coordinate: column')
        p1y = input()        
        try:
            if state[int(p1x),int(p1y)] != 0:
                print('Invalid, try again.')
            else:
                state[int(p1x),int(p1y)] = 1
                valid = False
        except:
            print('Invalid, try again.')
    if check_win(state):
            print('you win!')
            break
    try:
        # 1. dynamic programming logic: cycle through available coords, if can win now, choose that cord
        # 2. otherwise min continuation value, that is, choose a coord to block p1's win, if possible
        # 3. if no threats, randomize (or randomize blocking coords)
        
        avail_cords = [(i,j) for i,j in zip(*np.where(state==0))] 
        # 1. dynamic programming logic: cycle through available coords, if can win now, choose that cord
        win_cord = None
        winning = False
        for cord in avail_cords:
            temp_state = state.copy()
            temp_state[cord] = -1
            if check_win(temp_state):
                winning = True
                win_cord = cord
        if winning:
            state[win_cord] = -1
        # 2. otherwise min continuation value, that is, choose a coord to block p1's win, if possible
        else:
            possible_cords = []
            for cord in avail_cords:
                temp_state = state.copy()
                temp_state[cord] = -1
                temp_avail_cords = [(i,j) for i,j in zip(*np.where(temp_state==0))] 
                p1_win = False
                for cord2 in temp_avail_cords:
                    temp_state2 = temp_state.copy()
                    temp_state2[cord2] = 1
                    if check_win(temp_state2):
                        p1_win = True
                if not p1_win:
                    possible_cords.append(cord)
        # 3. if no threats, randomize (or randomize blocking coords)
            state[random.choice(possible_cords)] = -1        
    except:
        if not check_win(state):
            print('draw')
            break
    finally:
        if check_win(state):
            print('computer wins!')
            break
print(state)
state = np.array([[0, 0, 0], [0, 0, 0], [-1, 0, 0]])

[[ 0  0  0]
 [ 0  0  0]
 [-1  0  0]]
Enter coordinate: row
1
Enter coordinate: column
1
[[ 0  0  0]
 [ 0  1  0]
 [-1  0 -1]]
Enter coordinate: row
2
Enter coordinate: column
1
[[ 0 -1  0]
 [ 0  1  0]
 [-1  1 -1]]
Enter coordinate: row
0
Enter coordinate: column
0
[[ 1 -1 -1]
 [ 0  1  0]
 [-1  1 -1]]
Enter coordinate: row
1
Enter coordinate: column
0
computer wins!
[[ 1 -1 -1]
 [ 1  1 -1]
 [-1  1 -1]]
