Rayhan Momin

# Problem 1

In [1]:
import numpy as np

In [20]:
def prob1():
    A = np.array( [[3,-1,4], [1,5,-9]] )
    B = np.array( [[2,6, -5,3], [5,-8,9,7], [9,-3,-2,-3]] )
    return A@B

In [21]:
prob1()

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

# Problem 2

In [22]:
def prob2():
    A = np.array([[3,1,4],[1,5,9],[-5,3,1]])
    return -np.linalg.matrix_power(A,3) + 9*np.linalg.matrix_power(A,2) - 15*A

In [23]:
prob2()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Problem 3

In [24]:
def prob3():
    A = np.triu(np.ones((7,7)))
    B = np.tril(np.ones((7,7))*-1) + np.triu(np.ones((7,7))*5)  - np.diag([5,5,5,5,5,5,5])
    ABA = A@B@A
    ABA = ABA.astype(np.int64)
    return ABA

In [25]:
prob3()

array([[ -7,  -8,  -3,   8,  25,  48,  77],
       [ -6, -12, -12,  -6,   6,  24,  48],
       [ -5, -10, -15, -14,  -7,   6,  25],
       [ -4,  -8, -12, -16, -14,  -6,   8],
       [ -3,  -6,  -9, -12, -15, -12,  -3],
       [ -2,  -4,  -6,  -8, -10, -12,  -8],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7]])

# Problem 4

In [14]:
def copyArray(anArray):
    newArray = anArray.copy()
    mask = newArray < 0
    newArray[mask] = 0
    return newArray

In [15]:
copyArray(np.array([[-1,-1,-1],[2,-123,0], [2,1231,-3] ]))

array([[   0,    0,    0],
       [   2,    0,    0],
       [   2, 1231,    0]])

# Problem 5

In [64]:
def prob5():
    A = np.array([ [0,2,4], [1,3,5] ])
    B = np.array([[3,0,0], [3,3,0], [3,3,3]])
    C = np.array([[-2,0,0], [0,-2,0], [0,0,-2]])
    row1 = np.column_stack((np.zeros((3,3)), A.T, np.identity(3)))
    row2 = np.column_stack((A, np.zeros((2,2)), np.zeros((2,3))))
    row3 = np.column_stack((B, np.zeros((3,2)), C ))
    return np.vstack((row1,row2,row3))

In [65]:
prob5()

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

# Problem 6

In [77]:
def prob6(anArray):
    newArray = anArray.copy()
    temp = newArray.sum(axis=1)
    return newArray/temp.reshape((temp.shape[0],1))

In [78]:
B = np.array([[3,0,0], [3,3,0], [3,3,3]])

In [79]:
B

array([[3, 0, 0],
       [3, 3, 0],
       [3, 3, 3]])

In [80]:
prob6(B)

array([[1.        , 0.        , 0.        ],
       [0.5       , 0.5       , 0.        ],
       [0.33333333, 0.33333333, 0.33333333]])

# Problem 7

In [87]:
def return_max(sub_mat):
    assert type(sub_mat) is np.ndarray, 'input not numpy array'
    hort = sub_mat[0,:]
    vert = sub_mat[:,0]
    diag = np.diag(sub_mat)
    adiag = np.diag(np.fliplr(sub_mat))

    val_dict= {'hort': hort, 'vert':vert, 'diag': diag, 'adiag': adiag}
    prod_list = []

    for key, val in val_dict.items():
        prod_list.append((key,val,np.prod(val)))

    prod_list = sorted(prod_list, key = lambda x: x[2])

    return prod_list[-1]

In [91]:
def prob7Naive():
    mat = np.load('grid.npy')
    sub_mat_size = 4
    row_divs = mat.shape[0]-sub_mat_size
    col_divs = mat.shape[1]-sub_mat_size

    sub_mat_dat = []

    for i in range(col_divs):
        for j in range(row_divs):
            sub_mat = mat[i:i+4,j:j+4]
            sub_mat_dat.append(return_max(sub_mat) + (i,j))

    sub_mat_dat = sorted(sub_mat_dat, key = lambda x: x[2])

    print(sub_mat_dat[-1])

In [92]:
prob7Naive()

('adiag', array([89, 94, 97, 87]), 70600674, 12, 3)


In [107]:
def prob7():
    return max(np.max(mat[:,:-3]*mat[:,1:-2]*mat[:,2:-1]*mat[:,3:] ), 
              np.max(mat[:-3,:]*mat[1:-2,:]*mat[2:-1,:]*mat[3:,:] ),
              np.max(mat[:-3,:-3]*mat[1:-2,1:-2]*mat[2:-1,2:-1]*mat[3:,3:] ),
              np.max(mat[:-3,3:]*mat[1:-2,2:-1]*mat[2:-1,1:-2]*mat[3:,:-3] ))

In [108]:
prob7()

70600674